cc_test(
    name = "munkres_unit_test",
    srcs = [
        "munkres_unit_test.cpp",
    ],
    features = [
        "treat_warnings_as_errors",
        "strict_warnings",
        "test_warnings",
    ],
    deps = [
        "//modules/association/munkres",
        "//third_party/google_test:gtest",
        "//third_party/google_test:gtest_main",
    ],
)
